class Strings {
  static const String technoSaz_str = "تکنوساز";
  static const String madeWith_str = "Made with 🤎 by U.D";
  static const String letsGo_str = "بزن بریم!";
  static const String byGoogle_str = "با گوگلت وارد شو";
  static const String byEmail_str = "با ایمیلت وارد شو";
  static const String skip_str = "فعلا بیخیال ، مهمون ما باش.";
  static const String or_str = "یا";
  static const String enterPassword_str = "پسوردتو وارد کن";
  static const String creatAccont = "از اینجا ثبت نام کن";
  static const String createAccount_str = "فعلا بیخیال ، مهمون ما باش.";
  static const String more_str = "بیشتر";
  static const String recentArticles_str = "مقالات اخیر";
  static const String myArticles_str = "مقاله های من";
  static const String bookmarked_str = "نشان شده ها";
  static const String alarm_str = "اعلان ها";
  static const String system_str = "سیستم";
  static const String public_str = "عمومی";
  static const String empty_str = ".هیچ اعلانی ندارید";
  static const String liked_str = ".مقاله‌ی شما را لایک کرد";
  static const String published_str = ".مقاله‌ی جدیدی منتشر کرد";
  static const String comment_str = ".به مقاله‌ی شما نظر داد";
  static const String daysAgo_str = "روز پیش";
  static const String articleName_str = "زبان دارت";
  static const String hoursAgo_str = "ساعت پیش";
  static const String pm_str = "بعدازظهر";
  static const String am_str = "صبح";
  static const String new_str = "جدید";
  static const String writerName_str = "هری پاتر.";
  static const String titleOnBanner = "چطور میتونیم نویسنده خوبی باشیم ؟";
  static const String minutes = "دقیقه";
  static const String article_str = "مقاله";
  static const String savedArticle_str = "نشان شده ها";
  static const String welcome = "به تکنوساز خوش اومدی";
  static const String shouldLogIn = "برای ارسال مطلب باید حتما ثبت نام کنی";
  static const String verifiedEmail = "تبریک میگیم،ایمیل با موفقیت تایید شد.";
  static const String complateLogInInfo = "لطفا اطلاعات ثبت نام رو کامل کن.";

}
